gui:
    # Config relating to the commit length indicator
    commitLength:
        # If true, show an indicator of commit message length
        show: true

    # Nerd fonts version to use.
    # One of: '2' | '3' | empty string (default)
    # If empty, do not show icons.
    nerdFontsVersion: "3"

# Config relating to git
git:
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
    paging:
        # Value of the --color arg in the git diff command. Some pagers want this to be set to 'always' and some want it set to 'never'
        colorArg: always

        pager: delta --dark --paging=never

        # If true, Lazygit will use whatever pager is specified in `$GIT_PAGER`, `$PAGER`, or your *git config*. If the pager ends with something like ` | less` we will strip that part out, because less doesn't play nice with our rendering approach. If the custom pager uses less under the hood, that will also break rendering (hence the `--paging=never` flag for the `delta` pager).
        useConfig: false

        # e.g. 'difft --color=always'
        externalDiffCommand: ""
