code --install-extension aaron-bond.better-comments
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension calebporzio.better-phpunit
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eric-c-hansen.vscode-docker-phpunit
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension felixfbecker.php-debug
code --install-extension jinsihou.diff-tool
code --install-extension johnpapa.vscode-peacock
code --install-extension junstyle.php-cs-fixer
code --install-extension karigari.chat
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension nikitaKunevich.snippet-creator
code --install-extension octref.vetur
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryannaddy.laravel-artisan
code --install-extension sleistner.vscode-fileutils
code --install-extension SonarSource.sonarlint-vscode
code --install-extension tomoki1207.pdf
code --install-extension vscodevim.vim
code --install-extension whatwedo.twig
