##### Resolve XDG config dir safely
if-shell 'test -n "$XDG_CONFIG_HOME"' {
  set -g @xdg_config_home "$XDG_CONFIG_HOME"
} {
  set -g @xdg_config_home "$HOME/.config"
}

## Status Bar Customization
# Show prefix key indicator
set -g status-left '#[fg=colour237]#{?client_prefix,#[fg=colour214],} *'
# Display session name
set -ga status-left '#[bg=colour237,fg=colour214] #S '
# Show current date and time
set -g status-right ' #[fg=colour244]%Y-%m-%d %H:%M '
# Show current user
set -ga status-right '#[bg=colour214,fg=colour237] #(whoami) '

## Pane Border Styling
# Darker gray for inactive panes
set -g pane-border-style fg=colour239
# Bright yellow for active panes
set -g pane-active-border-style fg=colour214
# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Window Numbering starting at 1
set -g base-index 1
## Windows List Customization
# Format for inactive windows: window ID (I) and window name (W)
setw -g window-status-format ' #[fg=colour244]#I #[fg=colour250]#W '
# For active window
setw -g window-status-current-format '#[bg=colour214,fg=colour237]#I #W'
## General formatting for active window: left rounded icon, window ID, zoom
# icon if zoomed, window name, right rounded icon
setw -g window-status-current-format '#[bg=colour237,fg=colour214]' # Left rounded icon
setw -ga window-status-current-format '#[bg=colour214,fg=colour237]#I' # Window ID
setw -ga window-status-current-format '#{?window_zoomed_flag, 󰘖,}' # Zoom icon
setw -ga window-status-current-format ' #W' # Window name
setw -ga window-status-current-format '#[bg=colour237,fg=colour214]' # Right rounded icon

# List of plugins
set -g @plugin 'RyanMacG/tpm-redux'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -gF @tpm_plugins_path "#{@xdg_config_home}/tmux/plugins"

# If TPM-Redux isn't installed, please install it and run
# `tmux source ~/.config/tmux/tmux.conf.`
if 'test ! -d #{@xdg_config_home}/tmux/plugins/tpm-redux' {
  run 'git clone https://github.com/RyanMacG/tpm-redux #{@tpm_plugins_path}/tpm-redux \
    && #{@tpm_plugins_path}/tpm-redux/bin/install_plugins \
	|| echo "tmux: failed to install tmux-redux"'
}
#
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '#{@tpm_plugins_path}/tpm-redux/tpm'
